apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-repositories-pvc
  namespace: tas-mcp
  labels:
    app.kubernetes.io/name: git-mcp-server
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard # Adjust based on your cluster's storage classes

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tas-mcp-logs-pvc
  namespace: tas-mcp
  labels:
    app.kubernetes.io/name: tas-mcp-server
    app.kubernetes.io/component: storage
spec:  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-mcp-logs-pvc
  namespace: tas-mcp
  labels:
    app.kubernetes.io/name: git-mcp-server
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard