global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'tas-mcp-server'
    static_configs:
      - targets: ['tas-mcp-server:8080']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s

  - job_name: 'tas-mcp-server-health'
    static_configs:
      - targets: ['tas-mcp-server:8082']
    metrics_path: '/health'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 10s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 15s