version: '3.8'

services:
  # TAS MCP Server - Main federation server
  tas-mcp:
    build: .
    ports:
      - "8080:8080"   # HTTP API
      - "50051:50051" # gRPC API
      - "8082:8082"   # Health endpoint
    environment:
      - LOG_LEVEL=info
      - HTTP_PORT=8080
      - GRPC_PORT=50051
      - HEALTH_PORT=8082
      - GIT_MCP_ENDPOINT=http://git-mcp:3000
    volumes:
      - ./examples/config:/app/config
      - ./examples/data:/app/data
    depends_on:
      - git-mcp
    networks:
      - mcp-network

  # Git MCP Server - Official Git repository server
  git-mcp:
    image: python:3.11-slim
    ports:
      - "3000:3000"
    working_dir: /app
    environment:
      - MCP_SERVER_PORT=3000
      - REPOSITORY_PATH=/repositories
    volumes:
      - ./examples/repositories:/repositories:ro
      - ./examples/git-mcp:/app
    command: |
      bash -c "
        pip install mcp-server-git uvicorn fastapi &&
        python -m mcp_server_git --port 3000 --repository /repositories
      "
    networks:
      - mcp-network

  # Example client to test Git MCP integration
  test-client:
    build: 
      context: .
      dockerfile: examples/Dockerfile.test
    environment:
      - TAS_MCP_ENDPOINT=http://tas-mcp:8080
      - GIT_MCP_ENDPOINT=http://git-mcp:3000
    volumes:
      - ./examples/test-scripts:/app/tests
    depends_on:
      - tas-mcp
      - git-mcp
    networks:
      - mcp-network
    profiles:
      - test

networks:
  mcp-network:
    driver: bridge

volumes:
  repositories:
    driver: local