version: '3.8'

services:
  # TAS MCP Server - Main federation server
  tas-mcp:
    build: 
      context: ../../
      dockerfile: Dockerfile
      args:
        VERSION: ${TAS_MCP_VERSION:-1.1.0}
        BUILD_DATE: ${BUILD_DATE}
        VCS_REF: ${VCS_REF}
    image: tas-mcp/server:${TAS_MCP_VERSION:-1.1.0}
    container_name: tas-mcp-federation-server-v${TAS_MCP_VERSION:-1.1.0}
    hostname: tas-mcp-server
    ports:
      - "8080:8080"   # HTTP API
      - "50051:50051" # gRPC API
      - "8082:8082"   # Health endpoint
    environment:
      TAS_MCP_VERSION: ${TAS_MCP_VERSION:-1.1.0}
      GIT_MCP_VERSION: ${GIT_MCP_VERSION:-1.0.0}
      LOG_LEVEL: info
      HTTP_PORT: 8080
      GRPC_PORT: 50051
      HEALTH_PORT: 8082
      FEDERATION_ENABLED: "true"
      FEDERATION_AUTO_DISCOVERY: "true"
      SERVICE_NAME: tas-mcp-federation-server
      SERVICE_VERSION: ${TAS_MCP_VERSION:-1.1.0}
    volumes:
      - ../../config:/app/config:ro
      - ../../logs:/app/logs
      - tas_mcp_data:/app/data
    networks:
      - mcp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.tributary-ai.service=tas-mcp-server"
      - "com.tributary-ai.version=${TAS_MCP_VERSION:-1.1.0}"
      - "com.tributary-ai.component=federation-server"

networks:
  mcp-network:
    driver: bridge
    name: mcp-network

volumes:
  tas_mcp_data:
    driver: local