apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: tas-mcp-base

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - servicemonitor.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml

commonLabels:
  app: tas-mcp
  version: v1.0.0
  component: mcp-server

images:
  - name: tas-mcp
    newTag: latest