apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tas-mcp
  namespace: tas-mcp
  labels:
    app: tas-mcp
spec:
  selector:
    matchLabels:
      app: tas-mcp
      service: health
  endpoints:
  - port: health
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s