apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tas-mcp-staging

resources:
  - ../../base
  - hpa.yaml
  - ingress.yaml

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: tas-mcp
    count: 2

images:
  - name: tas-mcp
    newTag: staging